-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id text NOT NULL,
  employee_name text NOT NULL,
  date date NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['present'::text, 'leave'::text])),
  leave_type text CHECK (leave_type = ANY (ARRAY['sick'::text, 'personal'::text, 'vacation'::text, 'emergency'::text, 'other'::text])),
  leave_reason text,
  approver text,
  is_advanced_leave boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.attendance_summary (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id text NOT NULL,
  employee_name text NOT NULL,
  month integer NOT NULL,
  year integer NOT NULL,
  present_days integer DEFAULT 0,
  leave_days integer DEFAULT 0,
  total_working_days integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT attendance_summary_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_summary_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.budgets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid,
  amount numeric NOT NULL DEFAULT 0,
  fiscal_year integer NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT budgets_pkey PRIMARY KEY (id),
  CONSTRAINT budgets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT budgets_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  company character varying,
  email character varying,
  phone character varying,
  client_type character varying NOT NULL DEFAULT 'existing'::character varying CHECK (client_type::text = ANY (ARRAY['new'::character varying, 'existing'::character varying]::text[])),
  contact_person character varying,
  address text,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.event_attendees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  user_id uuid NOT NULL,
  user_name character varying NOT NULL,
  status character varying DEFAULT 'attending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT event_attendees_pkey PRIMARY KEY (id),
  CONSTRAINT event_attendees_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT event_attendees_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT event_attendees_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  start_time time without time zone,
  end_time time without time zone,
  is_all_day boolean DEFAULT false,
  event_type character varying NOT NULL DEFAULT 'general'::character varying,
  location character varying,
  hall_id uuid,
  created_by uuid NOT NULL,
  created_by_name character varying NOT NULL,
  created_by_role character varying NOT NULL,
  is_recurring boolean DEFAULT false,
  recurring_pattern character varying,
  max_attendees integer,
  current_attendees integer DEFAULT 0,
  requires_approval boolean DEFAULT false,
  approved_by uuid,
  approval_status character varying DEFAULT 'approved'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT events_hall_id_fkey FOREIGN KEY (hall_id) REFERENCES public.halls(id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.expense_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['accommodation'::text, 'per-diem'::text, 'vehicle-hiring'::text, 'program-cost'::text, 'meeting-cost'::text, 'other'::text])),
  amount numeric NOT NULL,
  description text,
  status text DEFAULT 'pending'::text,
  organization_id uuid,
  CONSTRAINT expense_items_pkey PRIMARY KEY (id),
  CONSTRAINT expense_items_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.travel_requests(id),
  CONSTRAINT expense_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.halls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  capacity integer,
  location character varying,
  amenities ARRAY,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT halls_pkey PRIMARY KEY (id),
  CONSTRAINT halls_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.leave_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id text NOT NULL,
  employee_name text NOT NULL,
  leave_type text NOT NULL CHECK (leave_type = ANY (ARRAY['sick'::text, 'personal'::text, 'vacation'::text, 'emergency'::text, 'other'::text])),
  reason text NOT NULL,
  approver_id text NOT NULL,
  approver_name text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  is_advanced boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.meeting_attendees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  user_id uuid,
  attendee_name character varying NOT NULL,
  attendee_email character varying,
  attendee_organization character varying,
  attendee_type character varying NOT NULL CHECK (attendee_type::text = ANY (ARRAY['internal'::character varying, 'external'::character varying]::text[])),
  attendance_status character varying DEFAULT 'invited'::character varying CHECK (attendance_status::text = ANY (ARRAY['invited'::character varying, 'attended'::character varying, 'absent'::character varying, 'declined'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT meeting_attendees_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_attendees_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id),
  CONSTRAINT meeting_attendees_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT meeting_attendees_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.meeting_deadline_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  assigned_to uuid NOT NULL,
  assigned_to_name character varying NOT NULL,
  assigned_by uuid NOT NULL,
  assigned_by_name character varying NOT NULL,
  assignment_type character varying DEFAULT 'meeting'::character varying CHECK (assignment_type::text = ANY (ARRAY['meeting'::character varying, 'action_item'::character varying, 'follow_up'::character varying]::text[])),
  deadline_date date NOT NULL,
  deadline_time time without time zone,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  description text,
  completion_status character varying DEFAULT 'assigned'::character varying CHECK (completion_status::text = ANY (ARRAY['assigned'::character varying, 'accepted'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'rejected'::character varying, 'overdue'::character varying]::text[])),
  accepted_at timestamp with time zone,
  completed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT meeting_deadline_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_deadline_assignments_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id),
  CONSTRAINT meeting_deadline_assignments_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT meeting_deadline_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id),
  CONSTRAINT meeting_deadline_assignments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.meeting_follow_ups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_meeting_id uuid NOT NULL,
  follow_up_meeting_id uuid NOT NULL,
  follow_up_type character varying DEFAULT 'general'::character varying CHECK (follow_up_type::text = ANY (ARRAY['general'::character varying, 'action_items'::character varying, 'review'::character varying, 'emergency'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT meeting_follow_ups_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_follow_ups_parent_meeting_id_fkey FOREIGN KEY (parent_meeting_id) REFERENCES public.meetings(id),
  CONSTRAINT meeting_follow_ups_follow_up_meeting_id_fkey FOREIGN KEY (follow_up_meeting_id) REFERENCES public.meetings(id),
  CONSTRAINT meeting_follow_ups_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.meeting_minutes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  content text NOT NULL,
  minute_order integer NOT NULL DEFAULT 1,
  is_action_item boolean DEFAULT false,
  assigned_to uuid,
  assigned_to_name character varying,
  due_date date,
  due_time time without time zone,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  completion_status character varying DEFAULT 'pending'::character varying CHECK (completion_status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'overdue'::character varying, 'cancelled'::character varying]::text[])),
  completion_percentage integer DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  estimated_hours numeric,
  actual_hours numeric,
  deadline_notes text,
  reminder_sent boolean DEFAULT false,
  reminder_date timestamp with time zone,
  completed_at timestamp with time zone,
  completed_by uuid,
  completed_by_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  responsibility text,
  serial_no integer DEFAULT 1,
  remarks text,
  flags text,
  is_done boolean DEFAULT false,
  toggled_by text,
  toggled_at timestamp with time zone,
  created_by_name text,
  updated_by_name text,
  CONSTRAINT meeting_minutes_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_minutes_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id),
  CONSTRAINT meeting_minutes_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT meeting_minutes_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id),
  CONSTRAINT meeting_minutes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.meetings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  task_id uuid,
  meeting_type character varying NOT NULL CHECK (meeting_type::text = ANY (ARRAY['internal'::character varying, 'external'::character varying]::text[])),
  client_id uuid,
  location character varying NOT NULL,
  location_type character varying NOT NULL CHECK (location_type::text = ANY (ARRAY['office'::character varying, 'online'::character varying, 'current_location'::character varying]::text[])),
  latitude numeric,
  longitude numeric,
  location_address text,
  meeting_date date NOT NULL,
  meeting_time time without time zone,
  duration_minutes integer,
  created_by uuid NOT NULL,
  created_by_name character varying NOT NULL,
  assigned_to uuid,
  assigned_to_name character varying,
  deadline_date date,
  deadline_time time without time zone,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  status character varying DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'rescheduled'::character varying, 'overdue'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT meetings_pkey PRIMARY KEY (id),
  CONSTRAINT meetings_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT meetings_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT meetings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT meetings_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT meetings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  request_id uuid,
  message text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  read boolean NOT NULL DEFAULT false,
  request_type character varying DEFAULT 'travel'::character varying,
  organization_id uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  domain character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.receipts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  expense_item_id uuid NOT NULL,
  original_filename text NOT NULL,
  stored_filename text NOT NULL,
  file_type text NOT NULL,
  upload_date timestamp with time zone DEFAULT now(),
  storage_path text,
  public_url text,
  organization_id uuid,
  CONSTRAINT receipts_pkey PRIMARY KEY (id),
  CONSTRAINT receipts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT receipts_expense_item_id_fkey FOREIGN KEY (expense_item_id) REFERENCES public.expense_items(id)
);
CREATE TABLE public.task_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  update_type character varying NOT NULL,
  old_value text,
  new_value text,
  remarks text,
  updated_by uuid,
  updated_by_name character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT task_updates_pkey PRIMARY KEY (id),
  CONSTRAINT task_updates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT task_updates_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  department_id uuid NOT NULL,
  assigned_to ARRAY,
  assigned_user_ids ARRAY,
  status USER-DEFINED DEFAULT 'Not Started'::task_status,
  priority USER-DEFINED DEFAULT 'Medium'::task_priority,
  rag_status USER-DEFINED DEFAULT 'Unrated'::rag_status,
  due_date date,
  start_date date,
  completion_date date,
  bottlenecks text,
  rag_takeaway text,
  remarks text,
  created_by uuid,
  created_by_name character varying,
  last_updated_by uuid,
  last_updated_by_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by_id uuid,
  approved_by_id uuid,
  approved_by_name character varying,
  approved_at timestamp with time zone,
  organization_id uuid,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_approved_by_id_fkey FOREIGN KEY (approved_by_id) REFERENCES public.users(id),
  CONSTRAINT tasks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT tasks_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT tasks_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES public.users(id)
);
CREATE TABLE public.time_log_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  time_log_id uuid NOT NULL,
  user_id uuid NOT NULL,
  user_name character varying NOT NULL,
  comment text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT time_log_comments_pkey PRIMARY KEY (id),
  CONSTRAINT time_log_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT time_log_comments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT time_log_comments_time_log_id_fkey FOREIGN KEY (time_log_id) REFERENCES public.time_logs(id)
);
CREATE TABLE public.time_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  user_id uuid NOT NULL,
  user_name character varying NOT NULL,
  task_type character varying NOT NULL CHECK (task_type::text = ANY (ARRAY['Desk Research'::character varying, 'Field Visit'::character varying, 'Report Writing'::character varying, 'Interview/Consultation Meetings'::character varying, 'Visuals and Designing'::character varying, 'Data Analysis/Interpretation'::character varying, 'Finance/Administrative Tasks'::character varying]::text[])),
  description text NOT NULL,
  date date NOT NULL,
  hours_spent numeric NOT NULL CHECK (hours_spent > 0::numeric AND hours_spent <= 24::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT time_logs_pkey PRIMARY KEY (id),
  CONSTRAINT time_logs_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT time_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT time_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.travel_group_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  travel_request_id uuid NOT NULL,
  member_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  organization_id uuid,
  CONSTRAINT travel_group_members_pkey PRIMARY KEY (id),
  CONSTRAINT travel_group_members_travel_request_id_fkey FOREIGN KEY (travel_request_id) REFERENCES public.travel_requests(id),
  CONSTRAINT travel_group_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT travel_group_members_member_user_id_fkey FOREIGN KEY (member_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.travel_request_status (
  id integer NOT NULL DEFAULT nextval('travel_request_status_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  CONSTRAINT travel_request_status_pkey PRIMARY KEY (id)
);
CREATE TABLE public.travel_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  employee_name text NOT NULL,
  department text NOT NULL,
  designation text NOT NULL,
  purpose text NOT NULL,
  travel_date_from timestamp with time zone NOT NULL,
  travel_date_to timestamp with time zone NOT NULL,
  total_amount numeric NOT NULL,
  request_type text NOT NULL CHECK (request_type = ANY (ARRAY['normal'::text, 'advance'::text, 'emergency'::text, 'group'::text])),
  previous_outstanding_advance numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approver_comments text,
  checker_comments text,
  project character varying,
  project_other character varying,
  purpose_type character varying,
  purpose_other character varying,
  location character varying,
  location_other character varying,
  transport_mode character varying,
  station_pick_drop character varying,
  local_conveyance character varying,
  ride_share_used boolean DEFAULT false,
  own_vehicle_reimbursement boolean DEFAULT false,
  phase integer NOT NULL DEFAULT 1,
  approver_id uuid,
  travel_details_approved_at timestamp with time zone,
  expenses_submitted_at timestamp with time zone,
  status_id integer,
  status text DEFAULT 'pending'::text,
  is_group_travel boolean DEFAULT false,
  is_group_captain boolean DEFAULT false,
  group_size integer,
  group_description text,
  group_members text,
  estimated_amount numeric DEFAULT 0,
  advance_notes text,
  emergency_reason character varying,
  emergency_reason_other character varying,
  emergency_justification text,
  emergency_amount numeric,
  needs_financial_attention boolean DEFAULT false,
  is_urgent boolean DEFAULT false,
  finance_comments text,
  organization_id uuid,
  CONSTRAINT travel_requests_pkey PRIMARY KEY (id),
  CONSTRAINT travel_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.users(id),
  CONSTRAINT travel_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fk_travel_requests_approver FOREIGN KEY (approver_id) REFERENCES public.users(id),
  CONSTRAINT travel_requests_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.travel_request_status(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL UNIQUE,
  password text NOT NULL,
  name text,
  role text NOT NULL CHECK (role = ANY (ARRAY['employee'::text, 'approver'::text, 'checker'::text, 'admin'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  designation text,
  department text,
  organization_id uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.valley_expenses (
  id uuid NOT NULL,
  request_id uuid NOT NULL,
  category text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'pending'::text,
  organization_id uuid,
  CONSTRAINT valley_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT valley_expenses_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.valley_requests(id),
  CONSTRAINT valley_expenses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.valley_requests (
  id uuid NOT NULL,
  employee_id uuid NOT NULL,
  employee_name text NOT NULL,
  department text NOT NULL,
  designation text NOT NULL,
  request_type text NOT NULL DEFAULT 'in-valley'::text,
  project text NOT NULL,
  purpose text NOT NULL,
  expense_date date NOT NULL,
  location text NOT NULL,
  description text NOT NULL,
  payment_method text NOT NULL,
  meeting_type text,
  meeting_participants text,
  total_amount numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text,
  approver_comments text,
  checker_comments text,
  travel_date_from date NOT NULL,
  travel_date_to date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  phase integer NOT NULL DEFAULT 1,
  travel_details_approved_at timestamp with time zone,
  expenses_submitted_at timestamp with time zone,
  approver_id uuid,
  emergency_reason character varying,
  emergency_reason_other character varying,
  emergency_justification text,
  emergency_amount numeric,
  needs_financial_attention boolean DEFAULT false,
  is_urgent boolean DEFAULT false,
  finance_comments text,
  organization_id uuid,
  CONSTRAINT valley_requests_pkey PRIMARY KEY (id),
  CONSTRAINT valley_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT valley_requests_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES public.users(id)
);